online-study_Flask/forms.py
from wtforms import Form, StringField,PasswordField
from wtforms.validators import Length,Email,EqualTo,InputRequired
# 参与注册验证的表单类
class Register_Form(Form):
    username = StringField(validators=[InputRequired(u"用户名不能为空"),Length(min=4,max=20)])
    passwd =PasswordField(validators=[InputRequired(u"密码不能为空"),Length(min=6,max=20)])
    email=StringField(validators=[InputRequired(u"邮件不能为空"),Email()])
    re_password = PasswordField(validators=[InputRequired(u"密码不能为空"),EqualTo("passwd",u"两次密码不一致")])

# 参与登录验证的表单类
class Login_Form(Form):
    user_name = StringField(validators=[InputRequired(u"用户名不能为空"),Length(min=4,max=20)])
    user_passwd =PasswordField(validators=[InputRequired(u"密码不能为空"),Length(min=6,max=20)])

online-study_Flask/app.py
from flask import Flask
from blueprints.login import bp as login_bp
from blueprints.root import bp as root_bp
from blueprints.box import bp as box_bp
from table_config import db,migrate,mail
import config
from flask import session
from flask import g
from model import User
# flask默认去templates文件夹下面找渲染的html文件

app = Flask(__name__)
app.register_blueprint(login_bp)
app.register_blueprint(root_bp)
app.register_blueprint(box_bp)
app.config.from_object(config)
db.init_app(app)
migrate.init_app(app,db)
mail.init_app(app)
# 这是获取登录状态函数,用于保持用户登录状态，只要session还在，用户下次进入该网站可以免登录
@app.before_request
def captcha_login():
    temp=session.get("user_id")
    if temp:
        user=User.query.get(temp)
        setattr(g,"user_id",user.id)
    else:
        setattr(g,"user_id",None)
if __name__ == '__main__':
    app.run(debug=True)

online-study_Flask/blueprints/box.py
from flask import Blueprint
bp=Blueprint("box",__name__,url_prefix="/box")
@bp.route('/')
def box_root():
    return "这是工具网页"

online-study_Flask/blueprints/login.py
import random
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for
from flask_mail import Message
from table_config import mail,db
from forms import Login_Form, Register_Form
from model import User
from sqlalchemy import or_
from model import Captcha
from flask import jsonify
from flask import session
# 实例化蓝图对象,该对象用于生成视图函数,这些函数都在蓝图的指定url为基础上绑定各自的url
bp=Blueprint("login",__name__,url_prefix='/login')

@bp.route('/',methods=["GET","POST"]) # 登录视图函数
def login():
    if request.method=="GET":
        return render_template('login/login.html',is_error=False)
    else:
        weqwe=request.form.get("quedin")
        form=Login_Form(request.form)
        if form.validate() and weqwe!='0':
            user=User.query.filter(or_(User.username==form.user_name.data,User.email==form.user_name.data)).all()
            if user and (user[0].password==form.user_passwd.data):
                session["user_id"]=user[0].id
                return render_template('/root.html')
            return redirect(url_for('root.root'))
        else:
            return render_template('login/login.html',is_error=True)
    
@bp.route('/register/', methods=['GET', 'POST'])
def register():   # 注册视图函数
    if request.method == "GET":
        return render_template('/login/register.html')
    else:
        # 将表单传入验证器类进行初始化
        form=Register_Form(request.form)
        # 从数据库中查找验证码
        true_captcha=Captcha.query.filter(or_(Captcha.email==form.email.data)).all()
        # 判断验证是否成功，以及查询对象是否存在
        if form.validate() and true_captcha:
            # 判断查找到的验证码是否匹配
            if request.form.get("captcha")==true_captcha[-1].captcha:
                # 创建用户并同步到数据库
                new_user=User(username=form.username.data , password=form.passwd.data , email=form.email.data)
                db.session.add(new_user)
                db.session.commit()
                # 重定向到登陆界面
                return redirect(url_for("login.login"))
        # 上述验证中出现错误则重定向到错误页面
        return render_template('login/register.html',is_error=True)
    
# 邮箱发送函数
@bp.route('/register/email_send/')
def email_send():
    # 获取get请求参数中的email
    email=request.args.get("email")
    # 生成验证码初始列表
    number_list=[str(i) for i in range(10)]
    captcha=''.join(random.choices(number_list,k=6))
    # 生成邮箱消息
    msg=Message(subject='懒人tool网站验证码发送',body=f'验证码:{captcha},谢谢您注册懒人tool在线学习平台,望您使用开心',
                recipients=[email])
    # 发送邮箱
    mail.send(msg)
    # 将生成的验证码和对应邮箱上传到数据库
    temp=Captcha(email=email,captcha=captcha)
    db.session.add(temp)
    db.session.commit()
    return jsonify({"code":200, "message": "success!", "data": None})

online-study_Flask/blueprints/root.py
from flask import Blueprint, request
from flask import render_template

bp=Blueprint("root",__name__,url_prefix="/")
@bp.route('/')
def root():
    return render_template('root.html')

@bp.route('/choujiang/',methods=["GET","POST"]) 
def choujiang():
    return render_template('/root/choujiang.html')

online-study_Flask/templates/base.html
<!-- 这个html是用来作为模板继承用的,用来减少代码的重复 -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 窗口名均写在同名占位符里 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 头部补充信息写在同名占位符里 -->
    {% block head %}{% endblock %}
</head>
<body>
    <!-- body具体实现均写在同名占位符里 -->
    {% block body %}
    {% endblock %}
</body>
</html>

online-study_Flask/templates/login/login.html
{% extends 'base.html' %} {% block title %} 登录 {% endblock %} {% block head %}
<script src="../../static/js/code.js"></script>
<link rel="stylesheet" type="text/css" href="../../static/css/code.css" />
<link rel="stylesheet" href="../../static/css/root.css" />

<link rel="stylesheet" href="../../static/css/bootstart/bootstrap.min.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap-grid.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap-grid.rtl.css" />
{% endblock %} {% block body %}
<div class="py-xl bg-cover bg-size--cover" style="background-image: url('../../static/image/w1.jpg');"><!--bg-size--cover 背景覆盖--><!--bg-cover 相对于他原本的位置定位--><!--py-xl 顶部底部pad-->
  <div class="container">
    <div class="col"><!--col 元素内部的每一列的列属性-->
      <div class="row justify-content-center"><!--justify-content-center 内容居中--><!--row 元素布局-->
        <div class="col-lg-4"><!--col-lg-4 元素内部的每一列布局-->
          <div class="card bg-info text-white"><!--text-white 白色纯文本--><!--bg-info 背景蓝颜色--><!--card 可扩展内部容器-->
            <div class="card-body"><!--card-body 卡片主体-->
              <h4 class="h3 text-white pt-3 pb-5">用户登录</h4><!--pt-3 顶部pad--><!--pb-5 底部pad-->
              <form action="{{url_for('login.login')}}" method="post">
                <div class="form-group"><!--form-group 下边距-->
                  <label>用户名:</label>
                  <input type="text" name="user_name" class="form-control" placeholder="请输入用户名" /><!--form-control 控件设置-->
                </div>
                <div class="form-group">
                  <label>密码:</label>
                  <input type="password" name="user_passwd" placeholder="请输入密码" class="form-control" />
                </div>
                <div class="form-group">
                  <label>验证码：</label>
                  <input type="text" name="temp_password" id="input1" placeholder="请输入验证码" class="form-control" />
                </div>
                <div class="form-group">
                  <input type="text" id="checkCode" class="code form-control" style="width: 100px" />
                  <a href="#" onclick="createCode();" class="btn btn-block btn-lg bg-white mt-4">看不清楚</a>
                </div><!--bg-white 白背景--><!--mt-4 外边距--><!--btn 圆角按钮--><!--btn-lg 大按钮--><!--btn-block 块级按钮-->
                <div class="form-group">
                  <button onclick="validate();" type="text" id="myButton" name="quedin"
                    class="btn btn-block btn-lg bg-white mt-4">
                    确定
                  </button>
                  <a href="{{url_for('root.root')}}" class="btn btn-block btn-lg bg-white mt-4">取消</a>
                  <!--<input onclick="history.back(-1);" type="button" class="btn btn-block btn-lg bg-white mt-4"
                    value="取消" />-->
                </div>
                <div class="form-group">
                  <p style="color: red">
                    {% if is_error %} 用户错误! {% endif %}
                  </p>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

online-study_Flask/templates/login/register.html
{% extends 'base.html' %} {% block title %} 注册 {% endblock %} {% block head %}
<!-- 加载注册用的js代码 -->
<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-1.9.0.min.js"></script>
<script src="../../static/js/register.js"></script>
<link rel="stylesheet" type="text/css" href="../../static/css/code.css" />
<link rel="stylesheet" href="../../static/css/root.css" />

<link rel="stylesheet" href="../../static/css/bootstart/bootstrap.min.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap-grid.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap-grid.rtl.css" />
{% endblock %} {% block body %}
<div class="py-xl bg-cover bg-size--cover" style="background-image: url('../../static/image/w1.jpg');">
    <div class="container">
        <div class="col">
            <div class="row justify-content-center">
                <div class="col-lg-4">
                    <div class="card bg-info text-white">
                        <div class="card-body">
                            <h4 class="h3 text-white pt-3 pb-5">用户注册</h4>
                            <form action="{{url_for('login.register')}}" method="post">
                                <div class="form-group">
                                    <label>用户名: </label>
                                    <input type="text" name="username" class="form-control" placeholder="请输入用户名" />
                                </div>
                                <div class="form-group">
                                    <label>邮箱：</label>
                                    <!-- 邮箱用来发送邮件验证码 -->
                                    <input type="text" name="email" class="form-control" placeholder="请输入邮箱" />
                                </div>
                                <div class="form-group">
                                    <label>验证码：</label>
                                    <input type="text" name="captcha" class="form-control" placeholder="请输入验证码" />
                                </div>
                                <div class="form-group">
                                    <!-- 这个button标签的操作由js文件实现 -->
                                    <button type="button" id="button" class="btn btn-block btn-lg bg-white mt-4">
                                        获取验证码
                                    </button>
                                </div>
                                <div class="form-group">
                                    <label>密码: </label>
                                    <input type="password" name="passwd" class="form-control" placeholder="请输入密码" />
                                </div>
                                <div class="form-group">
                                    <label>确认密码: </label>
                                    <input type="password" name="re_password" class="form-control"
                                        placeholder="请确认密码" />
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-block btn-lg bg-white mt-4">
                                        注册
                                    </button>
                                    <!-- 使用js实现回到登陆界面 -->
                                    <a href="{{url_for('root.root')}}" class="btn btn-block btn-lg bg-white mt-4">取消</a>
                                </div>
                                <div class="form-group">
                                    <p style="color: red">
                                        {% if is_error %} 用户错误! {% endif %}
                                    </p>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

online-study_Flask/templates/root.html
{% extends 'base.html' %} {% block title %} 懒人tool {% endblock %} {% block
head %}
<!-- 定义主页背景色的CSS样式 -->
<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-1.9.0.min.js"></script>
<script src="../../static/js/bootstrap.bundle.min.js"></script>

<link rel="stylesheet" href="../../static/css/root.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap.min.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap-grid.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap-grid.rtl.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap-reboot.min.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap-utilities.css" />
{% endblock %} {% block body%}
<nav class="navbar navbar-expand-lg navbar-transparent navbar-dark bg-dark py-4">
    <!--py-4 填充导航条顶部底部--><!--bg-dark 设置透明度--><!--navbar-dark 导航每个元素字体的颜色--><!--navbar-expand-lg 导航行或列及对齐形式--><!--navbar-transparent 导航整体设置--><!--navbar 导航边框设置-->
    <div class="container"><!--container 容器设置-->
        <h1 class="navbar-brand">欢迎来到懒人tool!</h1><!--navbar-brand 导航纯文本设计-->
        <div class="navbar-collapse offcanvas-collapse"><!--offcanvas-collapse 侧边滑动导航 --><!--navbar-collapse 折叠导航 -->
            <ul class="navbar-nav ml-auto align-items-lg-center">
                <!--align-items-lg-center 在其网格区域内的块向轴上的中心对齐 --><!--ml-auto 元素居右 --><!--navbar-nav 列表整体设计 -->
                <li class="nav-item dropdown"><!--dropdown 下拉菜单--><!--nav-item 元素设置-->
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-haspopup="false"
                        aria-expanded="false">工具栏</a><!--show js处理，隐藏元素--><!--aria-expanded 展开状态--><!--data-bs-toggle 触发事件--><!--dropdown-toggle 切换按钮-->
                    <ul class="dropdown-menu"><!--dropdown-menu 下拉菜单设计-->
                        <li>
                            <a class="dropdown-item" href="{{url_for('root.choujiang')}}">抽奖</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{{url_for('root.choujiang')}}">抽奖</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{{url_for('root.choujiang')}}">抽奖</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{{url_for('root.choujiang')}}">抽奖</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item"><!--nav-item 元素设置--><!--active 元素背景设置-->
                    <a href="{{url_for('login.login')}}" class="nav-link">登录</a><!--nav-link 元素名字设置-->
                </li>
                <li class="nav-item">
                    <a href="{{url_for('login.register')}}" class="nav-link">注册</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="menu">
</div>
{% endblock %}

online-study_Flask/templates/root/choujiang.html
{% extends 'base.html' %}

{% block title %}
抽奖
{% endblock %}


{% block head %}
<!-- 加载注册用的js代码 -->
<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-1.9.0.min.js"></script>
<script src="../../static/js/choujiang.js"></script>

<link rel="stylesheet" href="../../static/css/bootstart/bootstrap.min.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap-grid.css" />
<link rel="stylesheet" href="../../static/css/bootstart/bootstrap-grid.rtl.css" />
{% endblock %}

{% block body%}
<div>
    <input type="text" id="anseron" class="code form-control"/>
    <a href="#" onclick="choujiang();" class="btn btn-block btn-lg bg-white mt-4">开始抽奖</a>
</div>
{% endblock %}